apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  selector:
    app: books-app
  type: NodePort
  ports:
    - name: books-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
